Vagrant.configure("2") do |config|
  NodeCount = 1

  (1..NodeCount).each do |i|
      config.vm.define "haproxy_#{i}" do |haproxy|
          haproxy.vm.box = "oraclelinux/7"
          haproxy.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json"
          haproxy.vm.network "private_network", name: "vboxnet1", ip: "172.19.3.2#{i}"
          haproxy.vm.network "private_network", name: "vboxnet2", ip: "172.19.5.4#{i}"
          haproxy.vm.hostname = "haproxy-0#{i}"
          haproxy.vm.provision "shell", path: "disable-selinux.sh"
      end
  end
end
